package com.peaslimited.shoppeas.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;
import java.util.ArrayList;

/**
 * This class represents a consumer's transactions.
 * It utilizes Lombok annotations to automatically generate getter, setter,
 * toString, equals, hashCode, as well as constructors.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderHistory {

    /**
     * The unique identifier for the transaction, as generated by firebase.
     */
    @Id
    private String oid;
    /**
     * A list of transaction IDs associated with the consumer for the specific order placed.
     */
    private ArrayList<String> orders; //list of tid
    /**
     * The timestamp of when the order was placed.
     */
    private LocalDate date;
    /**
     * The total price of all orders placed.
     */
    private double total_price;
    /**
     * The consumer's ID of the consumer who placed the order.
     */
    private String uid;
}
